Calculator styling
elisha2kyakpo1/math-magicians pull request #3
Opened 2021-08-10 13:21 UTC by elisha2kyakpo1

**Content**

1. Created a calculator class component.
2. Added styling to much the gived design.

2021-08-10 14:19 UTC, henatan99 requested changes
Hi @elisha2kyakpo1 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._
- [ ] There are typos in your PR comment. Kindly fix them. :pray: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 14:19 UTC, henatan99 commented on src/App.js
> -      <header className="App-header">
- [ ] The `App.js` component should be class-based as per the project's requirements even though functional component is very correct. Please change this functional component to a class component. :+1: 
- [ ]  You also need to import `React, {Component}` when you convert the functional component to class component extended from `React Component`.

2021-08-10 14:19 UTC, henatan99 commented on src/components/Calculator.css
> +  font-size: 30px;
- [ ] I suggest the font size of the input field text better be equal or greater than the button texts font size. I believe it increases the visibility of the calculator operations. :relaxed: 
- [ ] You did not use the correct division symbol. Kindly fix that. :symbols: 
![image](https://user-images.githubusercontent.com/64894927/128883533-d3d07fbb-9475-4b6c-9e0b-5b31159f482f.png)

2021-08-10 14:50 UTC, Dipeshtwis requested changes
Hi @elisha2kyakpo1, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
_Check the comments under the review._
- [ ] As said in the previous review, Please fix the typo. Instead of `Added styling to much the gived design`, it should be `Added styling to match the given design`.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 14:50 UTC, Dipeshtwis commented on src/components/Calculator.js
> +              <button type="button" className="o-buttons" value="">%</button>
- [ ] The value of this button should be  `÷` instead of `%`. Below is the button shown inside the green circle. 

![Screenshot from 2021-08-10 20-12-46](https://user-images.githubusercontent.com/22434660/128888471-67cd4824-c790-4d08-8d1b-38090713dc3d.png)

2021-08-10 18:21 UTC, mricanho requested changes
Hi @elisha2kyakpo1, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] Unfortunately, you didn't do the last mandatory change that the last code reviewers pointed out, please fix the symbol in your design to match the original design.

Mandatory requirement:

![imagen](https://user-images.githubusercontent.com/60631456/128913556-056bbccf-7a79-4aba-8b91-0ff658fdd011.png)

Original design:

![imagen](https://user-images.githubusercontent.com/60631456/128913639-f1be64f8-4eb1-49be-815b-0dc8e7216405.png)

Your design:

![imagen](https://user-images.githubusercontent.com/60631456/128913911-cdb2a6ae-803a-45b3-bdcf-02f77ac22d45.png)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 18:56 UTC, elisha2kyakpo1 commented
Hi @mricanho
Hope you are doing fine, look into this issue closely, I pushed before Github had problems, I just remained with updating the comment for the PR. Unfortunately, Github did not have that record even. When things were restored that's when I submitted. Check again and see where the commit is located. This is not my problem, please.

2021-08-11 08:22 UTC, SpaYco reviewed
Hello 👋,

_This is an additional review as a result of the second opinion request._

I can see that the reviewer checked https://github.com/elisha2kyakpo1/math-magicians/pull/3/commits/b100c828d9267d4723dd5dfe40bae20d842c0be4 instead of https://github.com/elisha2kyakpo1/math-magicians/pull/3/commits/b9a83e8e881ebb6f2e8d2e4c052d691a513c7261

Also, this is a tiny change and we wouldn't block you for it, so we'll approve this project for you, the status of the project will be updated soon, you can continue with the rest of the projects

Keep rocking 🚀!

2021-08-11 09:42 UTC, elisha2kyakpo1 commented
Thanks @SpaYco

2021-08-11 09:42 UTC, merged